@startuml
package singleton{
    class App{
        + main()
    }
    abstract class Hero{
        - gender
        + superPower
        + isHuman()
        - isMarried()
    }

    class Superman{
        - gender
        + superPower
        + fly()
        + isHuman()
        - isMarried()
    }

    class Batman{
        - gender
        + superPower
        + isHuman()
        + isMarried()
        + kill()
    }

    Hero <|-- Superman
    Hero <|-- Batman
    Hero <-- App
    note left on link #white : use
}
@enduml